name: Publish to Maven Central

on:
  push:
    tags:
      - '*.*'
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Tag
        id: set_tag
        run: |
          set appVersion = ${{ github.ref_name }}
          echo "::set-tag-result is $appVersion"

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
#      - uses: gradle/gradle-build-action@v3
#      - name: Publish
#        run: ./gradlew publishAndReleaseToMavenCentral
#        env:
#          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
#          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
#          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_SECRETKEYRING }}
#          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
